os: Visual Studio 2015

environment:
  matrix:
    - target: x86_64-pc-windows-msvc
    - target: i686-pc-windows-msvc
    - target: x86_64-pc-windows-gnu
    - target: i686-pc-windows-gnu

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-host %target% --default-toolchain stable
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup toolchain install beta
  - rustup toolchain install nightly
  - ps: |
      Function test() {
        echo "Testing"
        rustup run stable cargo test $args 2>&1 | %{ "$_" }
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
        rustup run stable cargo test --release $args 2>&1 | %{ "$_" }
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }

        rustup run beta cargo test $args 2>&1 | %{ "$_" }
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
        rustup run beta cargo test --release $args 2>&1 | %{ "$_" }
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }

        rustup run nightly cargo test $args 2>&1 | %{ "$_" }
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
        rustup run nightly cargo test --release $args 2>&1 | %{ "$_" }
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
      }

build: false

test_script:
  - cargo fmt -- --check
  - cargo clippy
  - test
  - test --features large-files
  - test --no-default-features
  - test --no-default-features --features large-files
  - test --no-default-features --features fallback-buf
  - test --no-default-features --features fallback-buf,large-files
  - test --no-default-features --features fallback-bufreader
  - test --no-default-features --features fallback-bufreader,large-files